apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: eks-dev-testing-papertrl   # Ensure the namespace matches the pod's namespace
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc

