apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
  namespace: eks-dev-testing-papertrl   # Ensure the namespace matches the pod's namespace
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0fafac3a773722eed  # Replace with your EFS File System ID
