apiVersion: apps/v1
kind: Deployment
metadata:
  name: papertrl-vp-deployment
  namespace: eks-dev-testing-papertrl
  labels:
    app: papertrl-vp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: papertrl-vp
  template:
    metadata:
      labels:
        app: papertrl-vp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: papertrl-vp
        image: 194978441177.dkr.ecr.us-east-2.amazonaws.com/vp-service:latest
        ports:
        - name: http
          containerPort: 9002
        env:
        - name: DB_HOST
          value: "dev-eks.cawybcg7o5p2.us-east-2.rds.amazonaws.com" # Replace with your RDS endpoint
        - name: DB_PORT
          value: "3306" # Default MySQL/MariaDB port
        - name: DB_USERNAME
          value: "papertrl" # Replace with your DB username
        - name: DB_PASSWORD
          value: "ptmariadbcom" # Replace with your DB password
        imagePullPolicy: IfNotPresent
      nodeSelector:
        eks.amazonaws.com/nodegroup: backend-node-group  # Ensure it runs on the frontend node group