apiVersion: v1
kind: Service
metadata:
  name: papertrl-common
  namespace: dev  # Replace with your namespace
spec:
  selector:
    app: papertrl-common         # Ensure this matches the label in your deployment
  ports:
    - protocol: TCP
      port: 9008                # The port exposed by the service
      targetPort: 9008          # The port your container listens on
  type: ClusterIP               # Internal service (default type)
