apiVersion: v1
kind: Service
metadata:
  name: papertrl-frontend-service
  namespace: eks-dev-testing-papertrl
  labels:
    app: papertrl-ui
spec:
  type: LoadBalancer
  selector:
    app: papertrl-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      