apiVersion: v1
kind: Service
metadata:
  name: papertrl-integration
  namespace: eks-dev-testing-papertrl  # Replace with your namespace
spec:
  selector:
    app: papertrl-integration         # Ensure this matches the label in your deployment
  ports:
    - protocol: TCP
      port: 9006                # The port exposed by the service
      targetPort: 9006          # The port your container listens on
  type: ClusterIP               # Internal service (default type)
