apiVersion: v1
kind: Service
metadata:
  name: papertrl-tenant
  namespace: dev  # Replace with your namespace
spec:
  selector:
    app: papertrl-tenant         # Ensure this matches the label in your deployment
  ports:
    - protocol: TCP
      port: 9004                # The port exposed by the service
      targetPort: 9004          # The port your container listens on
  type: ClusterIP               # Internal service (default type)
