apiVersion: v1
kind: Service
metadata:
  name: papertrl-umm
  namespace: eks-dev-testing-papertrl  # Replace with your namespace
spec:
  selector:
    app: papertrl-umm         # Ensure this matches the label in your deployment
  ports:
    - protocol: TCP
      port: 9003                # The port exposed by the service
      targetPort: 9003          # The port your container listens on
  type: ClusterIP               # Internal service (default type)
