apiVersion: v1
kind: Service
metadata:
  name: papertrl-payment
  namespace: dev  # Replace with your namespace
spec:
  selector:
    app: papertrl-payment         # Ensure this matches the label in your deployment
  ports:
    - protocol: TCP
      port: 5060                # The port exposed by the service
      targetPort: 5060          # The port your container listens on
  type: ClusterIP               # Internal service (default type)
