apiVersion: v1
kind: Service
metadata:
  name: papertrl-auth
  namespace: eks-dev-testing-papertrl  # Replace with your namespace
spec:
  selector:
    app: papertrl-auth         # Ensure this matches the label in your deployment
  ports:
    - protocol: TCP
      port: 9000                # The port exposed by the service
      targetPort: 9000          # The port your container listens on
  type: ClusterIP               # Internal service (default type)
