apiVersion: v1
kind: Service
metadata:
  name: papertrl-proxy
  namespace: dev  # Replace with your namespace
spec:
  selector:
    app: papertrl-proxy         # Ensure this matches the label in your deployment
  ports:
    - protocol: TCP
      port: 8082                # The port exposed by the service
      targetPort: 8082          # The port your container listens on
  type: ClusterIP               # Internal service (default type)
