apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-testing-nginx-deployment
  namespace: eks-dev-testing-papertrl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: frontend_node_group  # Ensure it runs on the frontend node group
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 100
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/nginx.conf   # Correct mount path
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: eks-dev-testing-papertrl
data:
  nginx.conf: |
    server {
        listen 100;

        location / {
            proxy_pass http://backend-app-service:3000;   # Backend app service
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
