apiVersion: v1
kind: Service
metadata:
  name: eks-dev-nginx-service
  namespace: eks-dev-testing-papertrl
  labels:
    app: nginx-webserver
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 100
      targetPort: 100
      nodePort: 30000  # Optional: You can specify a port or let Kubernetes assign one automatically
