apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  namespace: eks-dev-testing-papertrl
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - backend-node-group
      containers:
      - name: backend-app
        image: node:14-alpine  # Updated image
        ports:
        - containerPort: 3000
        command: ["node", "-e", "require('http').createServer((req, res) => res.end('Hello World!')).listen(3000)"]
