apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: papertrl-proxy-ingress
spec:
  rules:
    - host: papertrl-proxy
      http:
        paths:
          - path: /proxy
            pathType: Prefix
            backend:
              service:
                name: papertrl-proxy
                port:
                  number: 8082
