apiVersion: batch/v1
kind: Job
metadata:
  name: git-clone-efs
  namespace: eks-dev-testing-papertrl
spec:
  template:
    spec:
      containers:
        - name: git-clone-container
          image: alpine/git:latest    # Use a git-capable image
          command:
            - /bin/sh
            - -c
            - |
              git clone https://github.com/your-org/your-repo.git /papertrl/github_repo
              # Optional sparse checkout if you only need part of the repo
              cd /papertrl/github_repo
              git sparse-checkout init --cone
              git sparse-checkout set 1.Testing-APP-papertrlAppFiles/papertrlAppFiles
              ln -s /papertrl/github_repo/1.Testing-APP-papertrlAppFiles/papertrlAppFiles /papertrl/data/papertrlAppFiles
          volumeMounts:
            - name: efs-papertrl
              mountPath: /papertrl    # Mount point for EFS
      restartPolicy: OnFailure

      nodeSelector:
        eks.amazonaws.com/nodegroup: backend-node-group  # Ensure it runs on the backend node group

      volumes:
        - name: efs-papertrl
          persistentVolumeClaim:
            claimName: efs-pvc  # PVC for EFS
