apiVersion: batch/v1
kind: Job
metadata:
  name: git-clone-efs
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: git-clone-container
          image: alpine/git:latest    # Use a git-capable image
          command:
            - /bin/sh
            - -c
            - |
              REPO_URL="https://github.com/kusal-viraj/eks-template-deploy.git"
              REPO_DIR="/papertrl/github_repo"
          
              # Check if the repository is already present by looking for a .git directory
              if [ -d "$REPO_DIR/.git" ]; then
              echo "Repository already exists, pulling the latest changes..."
              cd $REPO_DIR
              git pull origin master  # Replace 'master' with the branch you want to pull from
              else
              echo "Cloning the repository..."
              mkdir -p /papertrl/github_repo
              mkdir -p /papertrl/data
              mkdir -p /papertrl/logs
              git clone $REPO_URL $REPO_DIR
              fi
              
              # Optional sparse checkout if you only need part of the repo
              cd $REPO_DIR
              git sparse-checkout init --cone
              git sparse-checkout set 1.Testing-APP-papertrlAppFiles/papertrlAppFiles
              ln -s $REPO_DIR/1.Testing-APP-papertrlAppFiles/papertrlAppFiles /papertrl/data/
          volumeMounts:
            - name: efs-papertrl
              mountPath: /    # Mount point for EFS
      restartPolicy: OnFailure

      nodeSelector:
        eks.amazonaws.com/nodegroup: backend-node-group  # Ensure it runs on the backend node group

      volumes:
        - name: efs-papertrl
          persistentVolumeClaim:
            claimName: efs-pvc  # PVC for EFS
