apiVersion: batch/v1
kind: Job
metadata:
  name: git-clone-efs
  namespace: eks-dev-testing-papertrl
spec:
  template:
    spec:
      containers:
        - name: git-clone-container
          image: alpine/git:latest    # Use a git-capable image
          command:
            - /bin/sh
            - -c
            - |
              if [ -d "/papertrl/data/papertrlAppFiles/.git" ]; then
              echo "Git repository exists in /papertrl/data/papertrlAppFiles. Pulling latest changes."
              git -C /papertrl/data/papertrlAppFiles pull origin master
              else
              echo "Cloning the repository into /papertrl/data/papertrlAppFiles..."
              mkdir -p /papertrl/data/papertrlAppFiles  # Ensure the directory exists
              git clone 'https://github.com/kusal-viraj/eks-template-deploy.git' /papertrl/data/papertrlAppFiles
              git -C /papertrl/data/papertrlAppFiles sparse-checkout init --cone
              git -C /papertrl/data/papertrlAppFiles sparse-checkout set eks-template-deploy/1.Testing-APP-papertrlAppFiles/papertrlAppFiles
              
                  # Verify the contents of the directory after cloning
              echo "Contents of /papertrl/data/papertrlAppFiles:"
              ls -la /papertrl/data/papertrlAppFiles
              fi
          volumeMounts:
            - name: efs-papertrl
              mountPath: /papertrl    # Mount point for EFS
      restartPolicy: OnFailure

      nodeSelector:
        eks.amazonaws.com/nodegroup: backend-node-group  # Ensure it runs on the backend node group

      volumes:
        - name: efs-papertrl
          persistentVolumeClaim:
            claimName: efs-pvc  # PVC for EFS
